### PR TITLE
enhance(validator): add targeted post-deployment GPU readiness checks

### LINKED ISSUE #607: Enhance deployment-phase validation to reflect post-install workload readiness
> Note: this issue has been revised from its original version based on the discussions in the comments. The original scope (deploy.sh messaging/docs fix) is now handled separately in [#609](https://github.com/NVIDIA/aicr/pull/609).
>
> Follow-up note: the broader registry-driven work to make deployment-phase validation symmetric and deep for **all** components is now tracked in [#622](https://github.com/NVIDIA/aicr/issues/622). This issue remains intentionally scoped to strengthening the existing deployment phase for deployment completeness plus the targeted GPU readiness signals below.

## Summary

We already have most of the machinery for a deployer-neutral readiness check in `aicr validate`. The gap is not a missing standalone tool or a missing new phase; the gap is that the current `deployment` phase is still narrower than **post-install workload readiness**.

The proposal is to strengthen the existing `deployment` phase so that:

```bash
aicr validate --recipe recipe.yaml --phase deployment
```

answers the practical post-install question users care about: **is this cluster actually ready for GPU workloads now?**

Concretely, this issue is about:
- keep using the existing deployment phase
- preserve the existing baseline checks:
  - enabled namespaces are `Active`
  - declared `expectedResources` are healthy
- add the targeted GPU-specific readiness checks the phase was missing:
  - `skyhook-customizations`: Skyhook CR completion
  - `nvidia-dra-driver-gpu`: kubelet-plugin readiness
  - `gpu-operator`: `ClusterPolicy.status.state == ready`

So the main new value is the addition of the targeted Skyhook, DRA, and GPU Operator deep readiness checks on top of the preserved baseline deployment checks.

## Problem

Today, `deployment` validation is closer to:
- components were installed
- some expected resources exist
- basic operator/resource checks passed

That is still weaker than real post-install workload readiness for GPU bundles.

For example, the cluster may still be converging after install while:
- Skyhook tuning is still running
- the DRA kubelet plugin is not fully ready
- GPU components are present but not yet usable end-to-end

So the missing piece is not a new validator binary or a new CLI entrypoint. The missing piece is that the existing `deployment` phase does not yet include the specific readiness checks needed for post-install workload readiness.

## Scope Assumption

The scope of `--phase deployment` here is:
- deployment completeness for all enabled components, and
- the specific post-install GPU readiness signals needed to close the current gap

It is **not** intended to become:
- a generic per-component health-check aggregator
- a full end-to-end workload smoke test
- a replacement for broader conformance validation

## Approach

Keep the existing `deployment` phase. Do **not** add a new phase, a new flag, or a new tool for now.

Instead, strengthen the existing deployment phase so that:

```bash
aicr validate --recipe recipe.yaml --phase deployment
```

serves as the practical post-install workload readiness check.

The implementation target is:

- reuse the current deployment checks
- add deployment-completeness checks for enabled components
  - namespaces exist and are `Active`
  - declared `expectedResources` exist and are healthy
- add the missing GPU readiness checks
  - `skyhook-customizations`
    - require Skyhook CR completion (`status.status == complete`)
    - scope the check to **only the Skyhook CRs this recipe declares** (names extracted from the recipe's own `ComponentRef.ManifestFiles`), so unrelated Skyhooks on the cluster (stale from prior deploys, or from other tenants) do not widen the failure surface
    - skip gracefully when the Skyhook CRD is not registered on the cluster
  - `nvidia-dra-driver-gpu`
    - require the kubelet plugin DaemonSet to be ready, discovered deployer-neutrally by the chart's role-suffix convention (name ending in `-kubelet-plugin`) rather than by a hard-coded object name or release-scoped label
  - `gpu-operator`
    - require stronger operator readiness (`ClusterPolicy.status.state == ready`), not just deployment existence

All checks stay deployer-neutral: no Helm API calls, no reads of release metadata, no dependence on release-scoped labels. Every lookup is a plain Kubernetes API call against live-cluster object shape.

Because this reuses the existing CLI, day-N re-verification after scale-up or other runtime changes is also covered: run the same command again.

### 1. Reuse `recipes/checks/*` directly in deployment via Chainsaw

Pros:
- maximum reuse of existing component health checks
- one source of truth for per-component readiness

Cons:
- most of the richer checks are in Chainsaw `Test` format, for example [`skyhook-customizations` health check](https://github.com/NVIDIA/aicr/blob/main/recipes/checks/skyhook-customizations/health-check.yaml)
- the normal deployment validator image does not currently ship the `chainsaw` binary
- making this work would require validator image/build/release pipeline changes, not just validator logic changes
- it broadens `deployment` toward a general component-readiness framework, which is more than we need for this gap

### 2. Convert the needed deployment checks to raw-resource Chainsaw assertions

Pros:
- avoids shipping the external `chainsaw` binary
- still reuses part of the current check model

Cons:
- current checks are not written in that simpler format
- creates a second, reduced version of the same health checks
- still adds another assertion path to deployment for a relatively small targeted gap

### 3. Strengthen `deployment` with a small pure-Go implementation

Pros:
- consistent with the current Go-based deployment validator implementation in [`validators/deployment`](https://github.com/NVIDIA/aicr/blob/main/validators/deployment/main.go)
- keeps the runtime path pure Go / Kubernetes client based
- no validator image/runtime dependency changes
- directly addresses the actual gap in a narrow way

Cons:
- does not make deployment a generic component-readiness aggregator
- broader per-component health checks still remain in conformance / `recipes/checks/*`

## Rationale

We are choosing option 3.

This is the smallest deployer-neutral change that closes the real gap:
- it preserves the current `aicr validate --phase deployment` user flow
- it keeps the implementation consistent with the existing Go-based validator path
- it avoids pulling Chainsaw into the normal deployment validator runtime and build pipeline
- it gives us what we actually need now:
  - deployment completeness for enabled components
  - plus the specific Skyhook, DRA, and GPU operator readiness checks that `deploy.sh` currently misses

It also keeps the user flow simple:

```bash
aicr validate --recipe recipe.yaml --phase deployment
```

instead of introducing a new phase or a new separate tool, and keeps the design deployer-neutral:
- no extra `deploy.sh` readiness framework
- no deployer-specific wait logic in bash
- no new standalone readiness binary

Broader per-component Chainsaw health checks can remain in conformance or be revisited later if we decide `deployment` should grow into a more general readiness framework.

Expected implementation size is small: a narrow change in the existing deployment validator package plus targeted tests, not a new validator subsystem.

## Out of Scope

- Adding a new validation phase name just for readiness
- Reintroducing a `deploy.sh --wait-ready` implementation here
- Pulling the full Chainsaw-based component health-check model into the normal deployment validator path
- Broader bridge-Job / cleanup-Job architecture work discussed alongside [#516](https://github.com/NVIDIA/aicr/issues/516)

## Related

- Messaging/docs fix: [#609](https://github.com/NVIDIA/aicr/pull/609)
- Undeploy hardening / complexity lesson: [#602](https://github.com/NVIDIA/aicr/pull/602)
- Registry-driven all-components readiness follow-up: [#622](https://github.com/NVIDIA/aicr/issues/622)
- Longer-term chart-based bundle architecture: [#516](https://github.com/NVIDIA/aicr/issues/516)

## Acceptance

- `aicr validate --recipe recipe.yaml --phase deployment` covers deployment completeness for enabled components
- deployment validation includes Skyhook completion, DRA plugin readiness, and stronger `gpu-operator` readiness where the recipe enables those components
- on a fresh GPU cluster where install has completed but Skyhook / driver convergence is still in progress, `aicr validate --phase deployment` fails during that window and passes after convergence completes
- `aicr validate --phase deployment` does not fail on clusters where the Skyhook CRD is not registered, or on recipes that do not enable `skyhook-customizations`; the Skyhook check is skipped (or reported as N/A) in those cases
- `aicr validate --phase deployment` scopes Skyhook readiness to the Skyhook CR names this recipe declares (extracted from `ComponentRef.ManifestFiles`). Unrelated Skyhook CRs on the cluster (stale from previous deploys, or owned by another tenant) do not affect the result. An enabled `skyhook-customizations` ref with no extractable Skyhook names fails closed as a recipe misconfiguration.
- `aicr validate --phase deployment` applies the same skip/fail-closed logic to `gpu-operator`: when the `nvidia.com/v1` CRD is not registered, the `ClusterPolicy` check is skipped; when it is registered but the `cluster-policy` CR is absent, validation fails as a real gpu-operator misconfiguration. Non-`NotFound` discovery errors (RBAC denial, API server unreachable, transient 5xx) always fail closed rather than being treated as a missing CRD — a broken cluster must never silently pass this check.
- `aicr validate --phase deployment` locates the DRA kubelet-plugin DaemonSet by the upstream chart's role-suffix convention (`-kubelet-plugin`), not by a hard-coded object name or a release-scoped label. Custom `fullnameOverride` values and non-Helm deployers continue to be validated correctly; ambiguity (>1 match) and absence (0 matches) surface as explicit failures that include the DaemonSet names involved.
- the deployment phase stays strictly deployer-neutral: no Helm API calls, no reads of release metadata, no dependence on release-scoped labels. Every lookup is a plain Kubernetes API call against live-cluster object shape.
- covered by unit tests for the deployment validator and existing live-cluster verification flows (for example CUJ validation), without introducing a new phase

### PR DESCRIPTION
**Pull request by yuanchen8911**
## Summary

Strengthen `aicr validate --phase deployment` by adding the targeted GPU-workload readiness signals the current validator misses — Skyhook customizations, NVIDIA DRA driver, and GPU Operator (`ClusterPolicy`) — on top of the existing namespace and `expectedResources` checks.

Concretely, this PR:
- keeps using the existing deployment phase
- preserves the existing baseline checks:
  - enabled namespaces are `Active`
  - declared `expectedResources` are healthy
- adds the targeted GPU-specific readiness checks the phase was missing:
  - `skyhook-customizations`: Skyhook CR completion
  - `nvidia-dra-driver-gpu`: kubelet-plugin readiness
  - `gpu-operator`: `ClusterPolicy.status.state == ready`

So the main new value is the addition of the targeted Skyhook, DRA, and GPU Operator deep readiness checks on top of the preserved baseline deployment checks.

> Follow-up note: the broader registry-driven work to make deployment-phase validation symmetric and deep for **all** components is now tracked in [#622](https://github.com/NVIDIA/aicr/issues/622). This PR remains intentionally scoped to the targeted GPU readiness gap narrowed in `#607`.

The check stays strictly deployer-neutral: no Helm API calls, no dependence on Argo CD or any other deployer, no reads of release metadata, no release-identity assumptions. Every lookup is a plain Kubernetes API call against live-cluster object shape, so the command can be used as a standalone tool to verify any Kubernetes cluster's runtime install regardless of how the bundle was deployed (`deploy.sh`, Argo CD, kapp, helmfile, plain `kubectl apply`). Validated end-to-end on a real EKS H100 cluster.

## Motivation / Context

`#607` narrowed this follow-up to reusing and enhancing the existing deployment validator path instead of adding a new phase, flag, or Chainsaw runtime dependency. The previous deployment phase verified install/resource existence, but it did not cover the late-converging readiness signals that explain the post-install gap on fresh GPU clusters.

Fixes: #607
Related:
- #602
- #609
- #622
- #516

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Build/CI/tooling

## Component(s) Affected

- [ ] CLI (`cmd/aicr`, `pkg/cli`)
- [ ] API server (`cmd/aicrd`, `pkg/api`, `pkg/server`)
- [ ] Recipe engine / data (`pkg/recipe`)
- [ ] Bundlers (`pkg/bundler`, `pkg/component/*`)
- [ ] Collectors / snapshotter (`pkg/collector`, `pkg/snapshotter`)
- [x] Validator (`validators/deployment`)
- [ ] Core libraries (`pkg/errors`, `pkg/k8s`)
- [x] Docs/examples (`docs/`)
- [x] Other: E2E test harness (`tests/e2e`)

### Deployer-neutrality stance

The deployment-phase check stays strictly deployer-agnostic:
- No Helm API calls.
- No reads of Helm release metadata (secrets, ConfigMaps, or `helm list`).
- No dependence on release-scoped labels such as `app.kubernetes.io/instance`.

Every lookup is a plain Kubernetes API call against live-cluster object shape — labels, discovery, name conventions written into the chart templates themselves. The check is valid regardless of whether the bundle was deployed via `deploy.sh` (Helm), Argo CD (Helm or Kustomize), kapp, helmfile, or plain `kubectl apply`.

### Checks added or extended

- Enabled component namespaces must be `Active`.
- Declared `expectedResources` (Deployments, DaemonSets, etc.) must exist and be healthy.
- **Skyhook readiness (scope-limited to the recipe's own declarations):** the validator parses each `ComponentRef.ManifestFiles` of the `skyhook-customizations` component through the recipe data provider, extracts the `metadata.name` of every Skyhook resource declared, and verifies each one exists on the cluster with `status.status == "complete"`. A narrow Helm-template-tolerant regex extractor is used because manifests contain Helm `{{ ... }}` directives that break a full YAML parse. Skyhook CRs present on the cluster that are **not** declared by this recipe (stale from prior deploys, other tenants) are ignored. Fails closed when an enabled `skyhook-customizations` ref declares no extractable Skyhook names (recipe misconfiguration).
- **ClusterPolicy readiness:** Discovery on `nvidia.com/v1` is used up-front to disambiguate three cases the dynamic-client `Get` conflates:
  - CRD not registered (`IsNotFound` from discovery) → skip per `#607` acceptance.
  - CRD registered but `cluster-policy` CR absent → fail closed (gpu-operator installed but not reconciled).
  - Any other discovery error (RBAC 403, API 5xx, network timeout) → fail closed with a diagnostic pointing at RBAC / API reachability, so a transient discovery failure cannot silently mask readiness.
- **DRA kubelet-plugin readiness (role-suffix discovery):** the validator lists DaemonSets in the component namespace (timeout-bounded) and selects the one whose name ends in the upstream chart's hard-coded role suffix `-kubelet-plugin`. 0 matches → fail with the DaemonSets seen in the namespace. >1 matches → fail with the matched names. This is a chart-shape assumption (the upstream `nvidia-dra-driver-gpu` chart always names that DaemonSet `<fullname>-kubelet-plugin`), not a release-identity assumption — it survives `fullnameOverride` and non-Helm deployers. Readiness gate: both `DesiredNumberScheduled > 0` and `NumberReady == DesiredNumberScheduled`.

Skyhook is a cluster-scoped CR; the name-based `Get` path is cluster-scoped by construction, avoiding the namespaced-List-against-cluster-scoped-kind 404 that an earlier approach would have hit.

### Supporting changes

- `tests/e2e/run.sh` seeds a fake `ClusterPolicy` CRD (no status subresource — deliberate, and commented) plus a ready `cluster-policy` CR so deployment-phase E2E exercises the strengthened validator behavior.
- `docs/user/cli-reference.md` documents the expanded deployment phase: the full list of checks, the graceful-skip path when a CRD is absent, the fail-closed path for a missing CR with the CRD present, and the fail-closed path for non-NotFound discovery errors (with a concrete RBAC 403 example).

## Testing

```bash
# Local package run + coverage
GOFLAGS="-mod=vendor" go test -race -coverprofile=cover.out ./validators/deployment/...
go tool cover -func=cover.out | tail -1

# Repo coverage gate + full local gate
make test-coverage
unset GITLAB_TOKEN && make qualify
```

- `go test -race ./validators/deployment/...`: passed.
- `validators/deployment` coverage: substantially improved vs `origin/main` (new tests span the full behavioral surface below).
- `make test-coverage`: passed (above the `70%` project-wide threshold).
- `unset GITLAB_TOKEN && make qualify`: passed.

Added / updated regression coverage:

**DRA kubelet-plugin discovery**
- Happy path with the default chart name.
- Custom fullname-override name (e.g., `my-custom-gpu-kubelet-plugin`) still passes — proves the role-suffix approach is not coupled to the default name.
- Two DaemonSets with matching suffix fails with an ambiguity diagnostic listing both names.
- Unrelated DaemonSet in the same namespace (e.g., `node-exporter`) is ignored.
- Missing DaemonSet fails with a diagnostic that lists the DaemonSets actually seen in the namespace (for debugging).
- `0/0` and under-scheduled DaemonSet fail the readiness gate.

**Skyhook readiness**
- Cluster-scoped Get contract (regression against the earlier namespaced-List 404).
- CRD not registered → skip.
- Unrelated stale Skyhook CR on the cluster (even with the AICR label) does not affect the result when the expected CR is complete.
- Multiple expected Skyhooks with mixed failures → all failures surface in one error (not first-return).
- Enabled `skyhook-customizations` ref with no extractable Skyhook names → fail closed.
- Direct unit tests for `extractSkyhookNamesFromManifest`, including the `tuning-gke.yaml` case (metadata.name is `"tuning"`, not `"tuning-gke"`), Helm-template preamble tolerance, and templated-name skip.

**ClusterPolicy readiness**
- CRD-missing skip (via discovery).
- CRD present but CR missing → fail closed with "gpu-operator installed but CR missing?" diagnostic.
- Discovery returns non-NotFound (RBAC 403) → fail closed.
- Missing `status.state` → fail.

**Other**
- Namespace-not-`Active` → fail.
- `TestMain` forces the global recipe data provider to initialize before any `t.Parallel()` test calls `recipe.GetManifestContent`, working around a pre-existing race on lazy init in `pkg/recipe/provider.go`.

### Live-cluster validation

Ran `aicr validate --recipe recipe.yaml --phase deployment` against a real EKS H100 cluster (`aws-us-east-1-aicr-cuj2`) with the dynamo-platform inference recipe:

```text
phase=deployment status=passed validators=4 passed=4 failed=0 duration=26.824s
```

| Validator | Status |
|---|---|
| `operator-health` | passed |
| `expected-resources` | passed — exercised namespace `Active` for 10 namespaces, Skyhook `tuning` `status.status==complete` (name-based from the recipe's manifestFiles), `ClusterPolicy.status.state==ready` (discovery-gated), and the DRA kubelet-plugin DaemonSet via `-kubelet-plugin` suffix match |
| `gpu-operator-version` | passed |
| `check-nvidia-smi` | passed — 2/2 GPU nodes usable |

Exit code was `0`; CTRF report archived locally.

## Risk Assessment

- [x] **Low** — Isolated change, well-tested, easy to revert
- [ ] **Medium** — Touches multiple components or has broader impact
- [ ] **High** — Breaking change, affects critical paths, or complex rollout

**Rollout notes:** No migration or flag changes. This strengthens deployment-phase validation only.
- Skyhook and ClusterPolicy checks skip only when the corresponding CRD is not registered.
- Once the CRD exists, missing readiness objects are surfaced as real failures; non-NotFound discovery errors are never treated as skips.
- DRA kubelet-plugin discovery works for default-named and fullname-override'd deployments alike, and is deployer-neutral (no Helm or release-identity dependency).
- Skyhook readiness is scoped to the Skyhook CRs the recipe itself declares via `ManifestFiles`; unrelated Skyhooks on the cluster are ignored.

## Checklist

- [x] Tests pass locally (`make test` with `-race`)
- [x] Linter passes (`make lint`)
- [x] I did not skip/disable tests to make CI green
- [x] I added/updated tests for new functionality
- [x] I updated docs if user-facing behavior changed
- [x] Changes follow existing patterns in the codebase
- [x] Commits are cryptographically signed (`git commit -S`) — [GPG signing info](https://docs.github.com/en/authentication/managing-commit-signature-verification)

### CODE REVIEW

File: validators/deployment/expected_resources.go [hunk 1]
```diff
@@ -112,3 +293,18 @@ func buildResourceFetcher(ctx *validators.Context) (chainsaw.ResourceFetcher, er
...
+	}
+	if ctx.RESTConfig == nil {
+		return nil, errors.New(errors.ErrCodeInvalidRequest, "RESTConfig is not available")
+	}
+
+	dynClient, err := dynamic.NewForConfig(ctx.RESTConfig)
+	if err != nil {
+		return nil, errors.Wrap(errors.ErrCodeInternal, "failed to create dynamic client", err)
+	}
+	return dynClient, nil
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply validators/deployment/expected_resources.go:536]: Picked up in fbca793d. `buildResourceFetcher()` now goes through `getDynamicClient(ctx)` so the Chainsaw path uses the same lazy dynamic-client initialization as the other readiness checks.

File: validators/deployment/expected_resources_test.go [hunk 2]
```diff
@@ -0,0 +1,486 @@
...
+	if err == nil {
+		t.Fatal("expected error when DRA kubelet plugin DaemonSet is unhealthy")
+	}
+	if !strings.Contains(err.Error(), "DaemonSet nvidia-dra-driver/"+draKubeletPluginName) {
+		t.Fatalf("expected DRA DaemonSet context in failure, got: %v", err)
+	}
+	if !strings.Contains(err.Error(), "not healthy: 1/2 pods ready") {
+		t.Fatalf("expected unhealthy DaemonSet detail, got: %v", err)
+	}
+}
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply validators/deployment/expected_resources_test.go:470]: Picked up in fbca793d. Added a negative namespace-readiness test that fails when the component namespace is not Active, so regressions in `verifyNamespacesActive()` are covered now.

File: validators/deployment/expected_resources.go [hunk 3]
```diff
@@ -92,7 +128,152 @@ func checkExpectedResources(ctx *validators.Context) error {
...
+func verifyDRAKubeletPluginReady(ctx *validators.Context, namespace string) error {
+	if err := helper.VerifyResource(ctx.Ctx, ctx.Clientset, recipe.ExpectedResource{
+		Kind:      "DaemonSet",
+		Namespace: namespace,
+		Name:      draKubeletPluginName,
+	}); err != nil {
+		return err
+	}
+
+	fmt.Printf("  DaemonSet %s/%s: healthy\n", namespace, draKubeletPluginName)
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply validators/deployment/expected_resources.go]: Picked up in fbca793d. `verifyDRAKubeletPluginReady()` now fetches the kubelet-plugin DaemonSet after the generic health check and fails the readiness gate when it is `0/0` or otherwise has zero ready pods.

**Comment by yuanchen8911** [comment]
Related Slack discussion: https://nvidia.slack.com/archives/C0A457AAWUC/p1776444268331979?thread_ts=1776444020.536339&cid=C0A457AAWUC

**Comment by yuanchen8911** [comment]
Note that the scope of Issue 607 and PR 611 I opened is intentionally narrow and not meant to address all concerns. The goal is to improve the current AICR validator after deployment.

@lockwobr will investigate more advanced ideas, such as the bridge-job (issue #516), along with @pwittrock's ADR, in parallel as a longer-term solution.

A few notes on the proposal in issue #607 and PR #611 implementation:

- The validator is independent of the deployer
- Each component provides its own readiness status
- The validator performs a complete readiness check across all components, including Skyhook and GPU Operator

File: tests/e2e/run.sh [hunk 4]
```diff
@@ -680,10 +707,43 @@ spec:
...
         imagePullPolicy: IfNotPresent
 YAML
-  apply_rc=$?
+    return 1
+  fi
 
-  if [ $apply_rc -eq 0 ]; then
-    detail "Created fake GPU operator deployment (v24.6.0)"
+  kubectl wait --for=condition=available deployment/gpu-operator -n gpu-operator --timeout=60s 2>&1 || true
+}
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply tests/e2e/run.sh]: Fixed in c08cbe74. `setup_fake_gpu_operator_fixture()` now propagates `kubectl wait --for=condition=available` failure instead of swallowing it, and it cleans up any partially-created fake fixture before returning non-zero so the surrounding tests skip cleanly.

File: validators/deployment/expected_resources.go [hunk 5]
```diff
@@ -92,15 +147,371 @@ func checkExpectedResources(ctx *validators.Context) error {
...
+	seen := make(map[string]bool, len(refs))
+
+	for _, ref := range refs {
+		if ref.Namespace == "" || seen[ref.Namespace] {
+			continue
+		}
+		seen[ref.Namespace] = true
+
+		ns, err := ctx.Clientset.CoreV1().Namespaces().Get(ctx.Ctx, ref.Namespace, metav1.GetOptions{})
+		if err != nil {
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply validators/deployment/expected_resources.go]: Addressed in c08cbe74 for the API probes that actually accept a context. `verifyNamespacesActive()` and the dynamic `Get` paths in `verifySkyhookReady()` / `verifyClusterPolicyReady()` now use `ctx.Timeout(defaults.ResourceVerificationTimeout)`. I did not change the discovery helper call itself because `ServerResourcesForGroupVersion()` on the current client-go interface does not take a `context.Context`; making that specific probe timeout-bounded would require a different discovery-client path.

File: docs/user/cli-reference.md [hunk 6]
```diff
@@ -581,25 +580,39 @@ aicr validate [flags]
...
+- When `gpu-operator` is enabled: `ClusterPolicy` reports `status.state == ready`.
+- When `nvidia-dra-driver-gpu` is enabled: the kubelet-plugin DaemonSet is ready. Discovery is by the upstream chart's role-suffix convention — the validator finds the single DaemonSet in the component namespace whose name ends in `-kubelet-plugin`, so custom `fullnameOverride` values are handled automatically.
+
+**Graceful skip:** If a component is declared in the recipe but its CRD is not yet registered on the cluster (e.g., fresh cluster, operator chart not installed), the corresponding readiness check is skipped rather than failing. Once the CRD is present, the check runs and a missing CR is treated as a real failure — for example, if the `gpu-operator` CRD is registered but no `ClusterPolicy` CR exists, deployment validation fails with a "CR missing" diagnostic rather than silently passing. Other errors still fail closed: an RBAC denial on `skyhooks.skyhook.nvidia.com` returns HTTP 403 (not a `NoMatch`), so the validator surfaces it as a failure instead of silently skipping the Skyhook check.
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply docs/user/cli-reference.md:607]: Fixed in c08cbe74. The deployment-phase docs now call out the fail-closed skyhook-customizations case: if no Skyhook names can be extracted from the components `ComponentRef.ManifestFiles`, validation treats that as a recipe/configuration error instead of skipping.

File: tests/e2e/run.sh [hunk 7]
```diff
@@ -680,10 +707,43 @@ spec:
...
+
+cleanup_fake_gpu_operator_fixture() {
+  kubectl delete deployment gpu-operator -n gpu-operator --ignore-not-found 2>&1 || true
+  kubectl delete clusterpolicy cluster-policy --ignore-not-found 2>&1 || true
+  kubectl delete crd clusterpolicies.nvidia.com --ignore-not-found 2>&1 || true
+}
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply tests/e2e/run.sh:758]: Fixed in c08cbe74. The fake GPU Operator fixture now refuses to run if `deployment/gpu-operator`, `cluster-policy`, or `clusterpolicies.nvidia.com` already exist, and cleanup only deletes the resources this helper actually created. That avoids tearing down preexisting cluster-scoped GPU Operator state on a real cluster.

File: validators/deployment/expected_resources.go [hunk 8]
```diff
@@ -92,15 +147,377 @@ func checkExpectedResources(ctx *validators.Context) error {
...
+			continue
+		}
+		names = append(names, name)
+	}
+	return names
+}
+
+func verifyClusterPolicyReady(ctx *validators.Context) error {
+	// Use discovery to distinguish two cases the dynamic-client Get conflates:
+	//   1. CRD not registered ("CustomResourceDefinition clusterpolicies
```
Comment (mchmarny) [inline validators/deployment/expected_resources.go:371]: nit: when `ctx.DynamicClient` is nil, each call to `getDynamicClient` creates a new `dynamic.Interface` — and this function is called from both `verifySkyhookReady`, `verifyClusterPolicyReady`, and `buildResourceFetcher`. In production the field is almost certainly set, so this is just an inefficiency in the defensive fallback path. You could either:

- Cache the created client back onto `ctx.DynamicClient` (if the field is writable), or
- Create it once at the top of `checkExpectedResources` and pass it through.

Low priority since the nil path is unlikely in practice.

File: validators/deployment/expected_resources.go [hunk 9]
```diff
@@ -17,29 +17,82 @@ package main
...
+	draKubeletPluginSuffix = "-kubelet-plugin"
+
+	// aicrCreatedBy{Key,Value} document the label convention AICR manifests
+	// apply to resources they create ("app.kubernetes.io/created-by=aicr").
+	// The deployment-phase checks no longer use this label as a live-cluster
+	// filter — Skyhook readiness scopes by the exact CR names declared in
+	// the recipe's ManifestFiles, which is stronger than a label match —
+	// but tests still reference the constants when synthesizing fixture CRs
+	// that mirror production manifests.
+	aicrCreatedByLabelKey   = "app.kubernetes.io/created-by"
```
Comment (mchmarny) [inline validators/deployment/expected_resources.go]: nit: these two constants are only referenced in the test file (`skyhookWithStatus` fixture builder). Since both files are `package main`, they're accessible either way — but having production constants whose only purpose is documenting a label convention for test fixtures is a bit unusual. Consider moving them to the test file and making them test-local constants. The doc comment already explains the "why" well, so the documentation value survives the move.

File: validators/deployment/expected_resources.go [hunk 10]
```diff
@@ -92,15 +147,377 @@ func checkExpectedResources(ctx *validators.Context) error {
...
+		return nil
+	default:
+		return errors.Wrap(errors.ErrCodeInternal,
+			fmt.Sprintf("failed to discover %s resources (is the API server reachable and RBAC in order?)", gv), discErr)
+	}
+
+	dynClient, err := getDynamicClient(ctx)
+	if err != nil {
+		return err
+	}
```
Comment (mchmarny) [inline validators/deployment/expected_resources.go:261]: Nice — the discovery-gated skip with fail-closed on non-NotFound is exactly the right pattern. Clean three-way switch that avoids both false-passes (RBAC 403 silently skipped) and false-fails (CRD genuinely not installed yet). Same comment applies to the identical pattern in `verifySkyhookReady`.

File: validators/deployment/expected_resources.go [hunk 11]
```diff
@@ -17,29 +17,82 @@ package main
...
+	skyhookGVR = schema.GroupVersionResource{
+		Group: "skyhook.nvidia.com", Version: "v1alpha1", Resource: "skyhooks",
+	}
+)
+
 // checkExpectedResources verifies that all expected Kubernetes resources declared
 // in the recipe's componentRefs exist and are healthy in the live cluster.
 func checkExpectedResources(ctx *validators.Context) error {
 	if ctx.Recipe == nil {
 		return errors.New(errors.ErrCodeInvalidRequest, "recipe is not available")
```
Comment (mchmarny) [inline validators/deployment/expected_resources.go:73]: Good: filtering to enabled-only refs before the main loop is the right call. Worth noting this is a subtle behavioral change from the original code (which iterated *all* `ctx.Recipe.ComponentRefs`, including disabled ones, for `ExpectedResources` and `HealthCheckAsserts`). The `TestCheckExpectedResources_SkipsDisabledComponents` test covers it, so this is just a note for reviewers.

File: validators/deployment/expected_resources_test.go [hunk 12]
```diff
@@ -0,0 +1,1118 @@
...
+	k8sfake "k8s.io/client-go/kubernetes/fake"
+	clienttesting "k8s.io/client-go/testing"
+)
+
+// testDefaultDRADSName is the kubelet-plugin DaemonSet name the upstream
+// nvidia-dra-driver-gpu chart renders when no fullname override is in play.
+// Tests use it as a sane default fixture name, and a separate test exercises
+// an intentionally-different name to prove the role-suffix discovery works.
+const testDefaultDRADSName = "nvidia-dra-driver-gpu-kubelet-plugin"
+
```
Comment (mchmarny) [inline validators/deployment/expected_resources_test.go:47]: The test coverage here is genuinely excellent — the edge case matrix (CRD missing vs CR missing vs discovery failure, scoped vs stale Skyhook, custom DRA names, ambiguity guard) is thorough and each test name clearly states the invariant it pins. The `TestMain` workaround for the racy lazy-init is pragmatic and well-documented.

File: validators/deployment/expected_resources_test.go [hunk 13]
```diff
@@ -0,0 +1,1118 @@
...
+	for _, object := range f.objects {
+		if object.GetName() != name {
+			continue
+		}
+		if f.namespace != "" && object.GetNamespace() != f.namespace {
+			continue
+		}
+		return object.DeepCopy(), nil
+	}
+	return nil, stderrors.New("object not found")
```
Comment (mchmarny) [inline validators/deployment/expected_resources_test.go]: **medium: fake `Get` returns bare error — `IsNotFound` branch in `verifySkyhookReady` untested**

`stderrors.New("object not found")` won't match `apierrors.IsNotFound()`. In `verifySkyhookReady`, there's a specific branch:

```go
if apierrors.IsNotFound(getErr) {
    failures = append(failures, fmt.Sprintf("Skyhook %s: not found (recipe declared it but the cluster has no such CR)", name))
    continue
}
```

Because this fake returns a bare error, that branch is never exercised — tests would hit the generic `"failed to get: %v"` fallback instead. On a real cluster, a missing CR returns a proper 404 status error.

Fix: use `apierrors.NewNotFound` to match real API server behavior:

```go
return nil, apierrors.NewNotFound(
    schema.GroupResource{Group: f.resource.Group, Resource: f.resource.Resource}, name)
```

Then add a test that declares a Skyhook name in `ManifestFiles` but does *not* seed the corresponding CR, asserting the error contains `"not found (recipe declared it"`.

**Review by mchmarny — COMMENTED** [review]
Solid PR — the deployer-neutral design, discovery-gated CRD checks with fail-closed semantics, and scoped Skyhook readiness (by recipe manifest names, not cluster-wide label match) are well thought through. CI is fully green. Test coverage is thorough across the behavioral surface.

One medium finding: the test fake's `Get` method returns a bare `errors.New("object not found")` which doesn't satisfy `apierrors.IsNotFound()`, leaving the specific "recipe declared it but cluster has no such CR" branch in `verifySkyhookReady` untested. The rest are nits (test-only constants in production code, minor `getDynamicClient` caching opportunity).

Nothing blocks merge — the medium item is a test fidelity gap, not a production correctness issue.

File: validators/deployment/expected_resources_test.go (hunk 13 above)
Comment (yuanchen8911) [reply validators/deployment/expected_resources_test.go]: Fixed in 066fad56.

I updated the fake dynamic client to return `apierrors.NewNotFound(...)` instead of a bare `errors.New("object not found")`, so the test path now matches real API server behavior and exercises the `apierrors.IsNotFound()` branch in `verifySkyhookReady()`.

I also added `TestCheckExpectedResources_FailsWhenSkyhookCRMissing`, which registers the Skyhook CRD in discovery, declares `tuning` via `ManifestFiles`, omits the corresponding CR, and asserts the specific recipe-scoped diagnostic:

`Skyhook tuning: not found (recipe declared it but the cluster has no such CR)`

Local verification:
- `go test ./validators/deployment/...`
- `make lint`

File: validators/deployment/expected_resources.go (hunk 8 above)
Comment (yuanchen8911) [reply validators/deployment/expected_resources.go:371]: Fixed in 102b11bc.

I took the smaller of the two options here and cached the lazily constructed dynamic client back onto `ctx.DynamicClient` inside `getDynamicClient()`. That keeps the defensive nil-client fallback path cheap across `verifySkyhookReady()`, `verifyClusterPolicyReady()`, and `buildResourceFetcher()` without widening the function signatures.

Verification:
- `go test ./validators/deployment/...`
- `make lint`
- `unset GITLAB_TOKEN && make qualify`

File: validators/deployment/expected_resources.go (hunk 9 above)
Comment (yuanchen8911) [reply validators/deployment/expected_resources.go]: Fixed in 102b11bc.

I moved the fixture-only `app.kubernetes.io/created-by=aicr` label constants into `expected_resources_test.go`, so production code no longer carries symbols that are only used by the Skyhook test fixtures. The production comment value is preserved where it matters — in the test helper that synthesizes objects matching real manifests.

Verification:
- `go test ./validators/deployment/...`
- `make lint`
- `unset GITLAB_TOKEN && make qualify`

**Review by mchmarny — APPROVED** [review]
