### PR TITLE
fix: deploy.sh retry logic, CUJ2 doc cleanup, and test reporting guide

### LINKED ISSUE #335: [Bug]: deploy.sh is flakey with context deadline exceeded on CRD application
### Prerequisites

- [x] I searched existing issues and found no duplicates
- [x] I can reproduce this issue consistently
- [x] This is not a security vulnerability (use [Security Advisories](https://github.com/NVIDIA/aicr/security/advisories/new) instead)

### Bug Description

When running deploy.sh after having generated a bundle from a recipe (specifically CUJ2), I had some issues on deploying: 

- first deploy failed on a context deadline exceeded on CRD application
- second deploy attempted to do it idempotently, but ran into an issue with the webhook configurations that is being fixed
- third deploy failed but was prefaced by an undeploy.sh but the undeploy left some cert-manager CRDs around due to some resource policies
- fourth deploy failed prefaced by an undeploy.sh that succeeded
- fifth deploy succeeded

Would be nice if we had better retry mechanisms on this as the recovery is to just undeploy and deploy which is not ideal

### Impact

Low (minor issue)

### Component

Other / Unknown

### Regression?

Yes, this worked before (please specify version below)

### Steps to Reproduce

CUJ2.md

### Expected Behavior

I expect it flake less or have enough perpetual retry mechanisms to eventually succeed

### Actual Behavior

It flaked and didn't succeed for a bit.

### Environment

- AICR version (CLI `aicr version`, API image tag, or commit SHA):
- Install method (release binary / build from source / container image):
- Platform (eks/gke/aks/self-managed):
- Kubernetes version:
- OS (ubuntu/cos/other) + version:
- Kernel version:
- GPU type (h100/gb200/a100/l40/other):
- Workload intent (training/inference):

### Command / Request Used

_No response_

### Logs / Error Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lockwobr**
## Summary

- Add retry logic to the deploy.sh
- Cleaned a regex's in deploy.sh
- Add INT/TERM signal trap to deploy.sh template so Ctrl+C exits cleanly
- Document --retries 0 (fail-fast) in deploy.sh usage comment
- Remove non-existent hf-token-secret.yaml step from CUJ2 doc
- Add demos/README.md with demo index and session recording guide
- Add example CUJ2 test report in demos/examples/
- fix in install script to cross platform with linux

closes #335

## Motivation / Context

Fixes: 
Related: 

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Build/CI/tooling

## Component(s) Affected

- [ ] CLI (`cmd/aicr`, `pkg/cli`)
- [ ] API server (`cmd/aicrd`, `pkg/api`, `pkg/server`)
- [ ] Recipe engine / data (`pkg/recipe`)
- [ ] Bundlers (`pkg/bundler`, `pkg/component/*`)
- [ ] Collectors / snapshotter (`pkg/collector`, `pkg/snapshotter`)
- [ ] Validator (`pkg/validator`)
- [ ] Core libraries (`pkg/errors`, `pkg/k8s`)
- [ ] Docs/examples (`docs/`, `examples/`)
- [ ] Other: ____________

## Testing

```bash
# Commands run (prefer `make qualify` for non-trivial changes)
make qualify
```

## Risk Assessment

- [x] **Low** — Isolated change, well-tested, easy to revert
- [ ] **Medium** — Touches multiple components or has broader impact
- [ ] **High** — Breaking change, affects critical paths, or complex rollout

**Rollout notes:** 

## Checklist

- [x] Tests pass locally (`make test` with `-race`)
- [ ] Linter passes (`make lint`)
- [ ] I did not skip/disable tests to make CI green
- [ ] I added/updated tests for new functionality
- [ ] I updated docs if user-facing behavior changed
- [ ] Changes follow existing patterns in the codebase
- [x] Commits are cryptographically signed (`git commit -S`) — [GPG signing info](https://docs.github.com/en/authentication/managing-commit-signature-verification)

### CODE REVIEW

**Review by mchmarny — APPROVED** [review]

File: pkg/bundler/deployer/helm/templates/deploy.sh.tmpl [hunk 1]
```diff
@@ -42,6 +48,76 @@ helm_failed() {
...
+  while true; do
+    if "$@"; then
+      return 0
+    fi
+    attempt=$((attempt + 1))
+    if [[ ${attempt} -ge ${MAX_RETRIES} ]]; then
+      echo "ERROR: ${desc} failed after $((attempt + 1)) attempts"
+      return 1
+    fi
+    local wait_secs
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/deploy.sh.tmpl]: Bug: off-by-one in retry count and error message.

Tracing with `MAX_RETRIES=5`:
- Run 1: fails → attempt=1, 1≥5? no, retry
- Run 2: fails → attempt=2, 2≥5? no, retry
- Run 3: fails → attempt=3, 3≥5? no, retry
- Run 4: fails → attempt=4, 4≥5? no, retry
- Run 5: fails → attempt=5, 5≥5? yes → ERROR "failed after 6 attempts"

Result: 5 total runs (1 initial + **4** retries), but `MAX_RETRIES=5` implies 5 retries (6 total). The error message claims 6 attempts but only 5 ran.

Two fixes needed:
1. Change `-ge` to `-gt` so `MAX_RETRIES` retries actually happen
2. Change `$((attempt + 1))` to `${attempt}` in the error message (after the fix, `attempt` will equal the total run count when it exits)

Also affects `--retries 0`: currently runs once, then prints "failed after 2 attempts" — should say "1 attempt".

File: pkg/bundler/deployer/helm/templates/deploy.sh.tmpl [hunk 2]
```diff
@@ -18,22 +19,27 @@ SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 # Run helm commands from a temp directory to prevent local chart directories
 # (e.g., bundle/skyhook-operator/) from shadowing remote chart references.
 HELM_WORKDIR="$(mktemp -d)"
+trap 'rm -rf "${HELM_WORKDIR}"; exit 130' INT TERM
 trap 'rm -rf "${HELM_WORKDIR}"' EXIT
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/deploy.sh.tmpl]: Good: dual trap pattern (INT/TERM with explicit exit 130, EXIT for normal cleanup). The EXIT trap will fire after the INT trap's `exit 130`, so the temp dir gets `rm -rf` twice — harmless but correct. Clean approach.

**Review by mchmarny — CHANGES_REQUESTED** [review]
Good PR — retry logic, signal handling, CUJ2 doc cleanup, and cert-manager migration are all solid improvements. The cosign version detection simplification is a nice cleanup too.

Two issues need fixing before merge:

**Must fix:**
1. **retry() off-by-one** — `MAX_RETRIES=5` only gives 4 retries (5 total runs), not 5 retries (6 total) as documented. The error message also overcounts by 1. Fix: `-ge` → `-gt` and `$((attempt + 1))` → `${attempt}`.
2. **apply_ignoring_crd_race lost fail-safe** — The old inline code explicitly failed on unrecognized error formats (`elif [[ -z "${err_lines}" ]]`). The new function silently returns success when errors match neither CRD-race nor real-error patterns. This is a safety regression for unexpected kubectl failure modes.

**Nice to have:**
3. Validate `--retries` is numeric (avoid arithmetic errors on bad input)
4. Test assertion for cert-manager values checks `"enabled"` which is too generic

**Review by mchmarny — APPROVED** [review]
