### PR TITLE
fix(bundler): add pre-flight finalizer check to undeploy.sh (#406)

### LINKED ISSUE #406: [Bug]: undeploy.sh hangs when CRs have finalizers and controller is already uninstalled
### Prerequisites

- [x] I searched existing issues and found no duplicates
- [x] I can reproduce this issue consistently
- [x] This is not a security vulnerability (use [Security Advisories](https://github.com/NVIDIA/aicr/security/advisories/new) instead)

## Summary

  `undeploy.sh` hangs indefinitely when custom resources have finalizers that require their controller to process, but the controller has already been uninstalled.

  ## Root Cause

  The undeploy script uninstalls operators before cleaning up their custom resources. When CRD deletion triggers Kubernetes' built-in `customresourcecleanup.apiextensions.k8s.io` finalizer, it waits for all CR instances to be deleted. If
  those CRs have their own finalizers (e.g., `vllm-agg` DynamoGraphDeployment), the finalizer can't be processed because the controller (dynamo-platform) was already uninstalled. This creates a deadlock:

  CRD delete blocked → waiting for CR instances to be deleted
    └→ CR delete blocked → waiting for controller to process finalizer
         └→ controller → already uninstalled

  Ctrl+C does not help — re-running hits the same deadlock. The only workaround is manually patching finalizers:

  ```bash
  kubectl patch dynamographdeployment vllm-agg -n dynamo-workload \
    -p '{"metadata":{"finalizers":[]}}' --type=merge
```

  ## Proposed Fix

  Add a pre-flight check to `undeploy.sh` that scans for custom resources with finalizers in non-bundle namespaces (e.g., user workload namespaces). If found, warn the user and exit with instructions to clean up before re-running undeploy:

  WARNING: Found DynamoGraphDeployment "vllm-agg" in namespace "dynamo-workload" with active finalizers.
  These must be deleted before undeploy can proceed — the controller that processes
  their finalizers will be removed during teardown, causing an unrecoverable hang.

    kubectl delete dynamographdeployments -A --all

  Then re-run: ./undeploy.sh

  This avoids the complexity of automatic finalizer clearing while preventing the silent hang.

### Impact

Blocking (cannot proceed)

### Component

CLI (aicr)

### Regression?

Yes, this worked before (please specify version below)

### Steps to Reproduce

CUJ2 testing on EKS (2x p5.48xlarge H100). The dynamo-workload namespace with vllm-agg DGD was created by the user workload step. Running undeploy.sh hung after deleting dynamographdeployments.nvidia.com CRD.

### Expected Behavior

tell/warn the user, or fix the issue for them.

### Actual Behavior

hangs

### Environment

  - AICR v0.10.15
  - EKS v1.35.0-eks-3a10415
  - Ubuntu 24.04, kernel 6.14.0-1018-aws

### Command / Request Used

_No response_

### Logs / Error Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lockwobr**
## Summary

Add a pre-flight check to `undeploy.sh` that detects custom resources with active finalizers on CRDs owned by bundle operators. Warns the
user and exits before teardown to prevent the unrecoverable hang described in #406.

## Motivation / Context

`undeploy.sh` hangs indefinitely when CRs have finalizers that require their controller to process, but the controller has already been
uninstalled. The deadlock: `delete_release_cluster_resources()` deletes CRDs without `--wait=false` (line 81), the CRD's
`customresourcecleanup` finalizer blocks until all CR instances are gone, but CRs in user namespaces have controller-managed finalizers that
  can never be processed.

Fixes: #406
Related: N/A

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Build/CI/tooling

## Component(s) Affected

- [ ] CLI (`cmd/aicr`, `pkg/cli`)
- [ ] API server (`cmd/aicrd`, `pkg/api`, `pkg/server`)
- [ ] Recipe engine / data (`pkg/recipe`)
- [x] Bundlers (`pkg/bundler`, `pkg/component/*`)
- [ ] Collectors / snapshotter (`pkg/collector`, `pkg/snapshotter`)
- [ ] Validator (`pkg/validator`)
- [ ] Core libraries (`pkg/errors`, `pkg/k8s`)
- [ ] Docs/examples (`docs/`, `examples/`)
- [ ] Other: ____________

## Implementation Notes

**Pre-flight check** (`check_release_for_stuck_crds` / `check_crd_for_stuck_resources`):
- Uses `helm get manifest` to discover CRDs owned by each Helm component (generic — no hardcoded CRD group list needed)
- For each CRD, queries all namespaces for CR instances with non-empty `.metadata.finalizers`
- If found: lists blocking objects with their finalizer names, then exits with instructions
- Silently skips releases that aren't installed (`helm get manifest` failure → `return 0`)
- `--skip-preflight` flag to bypass when the user knows what they're doing

**Component manifest**: Lists all components that will be removed (with type tags: `[helm]`, `[kustomize]`, `[manifests]`) so users can see
exactly what undeploy will do — important for shared components like cert-manager.

**jq hard requirement**: Replaced the `HAS_JQ` soft-check with a hard gate. Removes ~8 branching guards throughout the script. jq was
already effectively required for CRD cleanup and webhook handling to work correctly.

**Stuck CRD handling**: Changed the existing silent force-clear of CRD finalizers to a warning with remediation commands. Force-clearing CRD
  finalizers can orphan CR data in etcd — the user should decide.

## Testing

```bash
make qualify   # all tests, lint, e2e pass; scan fails on pre-existing stdlib CVEs (go1.26.1→1.26.2)
```

**Unit tests** (`pkg/bundler/deployer/helm/helm_test.go`):
```
=== RUN   TestGenerate_UndeployScriptExecutable
--- PASS: TestGenerate_UndeployScriptExecutable (0.02s)
PASS
ok    github.com/NVIDIA/aicr/pkg/bundler/deployer/helm    1.81s
```

New assertions verify:
- jq is a hard requirement (no `HAS_JQ`)
- Pre-flight section exists and runs before component uninstall (index comparison)
- Pre-flight calls `check_release_for_stuck_crds` per component
- Helper functions exist and use `helm get manifest`
- Stuck CRD handling warns instead of force-clearing

**Manual Kind cluster test** (cert-manager + Issuer with fake finalizer):
```
❯ ./undeploy.sh
Undeploying Cloud Native Stack components...

  The following components will be removed (in order):
    [helm]       nvsentinel (nvsentinel)
    [helm]       nvidia-dra-driver-gpu (nvidia-dra-driver)
    [helm]       kai-scheduler (kai-scheduler)
    [helm]       gpu-operator (gpu-operator)
    [manifests]  skyhook-customizations
    [helm]       skyhook-operator (skyhook)
    [helm]       prometheus-adapter (monitoring)
    [helm]       k8s-ephemeral-storage-metrics (monitoring)
    [helm]       kube-prometheus-stack (monitoring)
    [helm]       cert-manager (cert-manager)
    [helm]       aws-efa (kube-system)
    [helm]       aws-ebs-csi-driver (kube-system)

Running pre-flight checks...

ERROR: Found custom resources with active finalizers that will block undeploy.
  After the operator is removed, these finalizers cannot be processed —
  causing an unrecoverable hang during CRD deletion.

  Delete these resources while their controller is still running,
  then re-run ./undeploy.sh

  cert-manager — issuers.cert-manager.io:
    test-workload/stuck-issuer  finalizers=[test.example.com/block-cleanup]

  To skip this check: ./undeploy.sh --skip-preflight
```

## Risk Assessment

- [x] **Low** — Isolated change, well-tested, easy to revert

**Rollout notes:** The pre-flight is additive — existing undeploy behavior is unchanged when no CRs with finalizers are found.
`--skip-preflight` provides an escape hatch. The jq hard requirement could block users without jq, but jq was already effectively required
for correct operation.

## Checklist

- [x] Tests pass locally (`make test` with `-race`)
- [x] Linter passes (`make lint`)
- [x] I did not skip/disable tests to make CI green
- [x] I added/updated tests for new functionality
- [ ] I updated docs if user-facing behavior changed
- [x] Changes follow existing patterns in the codebase
- [x] Commits are cryptographically signed (`git commit -S`)

### CODE REVIEW

File: pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl [hunk 1]
```diff
@@ -136,6 +148,93 @@ force_clear_namespace_finalizers() {
...
+# Pre-flight checks
+# ==============================================================================
+# Verify no custom resources with active finalizers exist for CRDs owned by
+# bundle operators. After helm uninstall removes the operator, CRs with
+# finalizers cannot be reconciled — blocking CRD deletion indefinitely.
+
+if [[ "${SKIP_PREFLIGHT}" == "true" ]]; then
+  echo "Skipping pre-flight checks (--skip-preflight)."
+else
+  echo "Running pre-flight checks..."
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl:217]: The temp file path is predictable (`${TMPDIR:-/tmp}/.aicr_preflight_details`) with no randomization. Two issues:

1. **Concurrent runs** — Two `undeploy.sh` invocations on the same node race on this file. One run's results could bleed into another's.
2. **Symlink attack** — A predictable temp file name in a world-writable directory is a classic TOCTOU vector. An attacker could symlink `.aicr_preflight_details` to a sensitive file; the `rm -f` + `>>` would truncate then append to it.

Use `mktemp` instead:
```bash
PREFLIGHT_DETAILS=$(mktemp "${TMPDIR:-/tmp}/.aicr_preflight_XXXXXX")
```
And the `rm -f` at the start becomes unnecessary (fresh file guaranteed).

File: pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl [hunk 2]
```diff
@@ -136,6 +148,93 @@ force_clear_namespace_finalizers() {
   done
 }
 
+# Check a single CRD for custom resource instances with active finalizers.
+# Appends details and remediation commands to the preflight temp files.
+# Args: $1 = CRD name, $2 = component name (for display)
+check_crd_for_stuck_resources() {
+  local crd_name="$1"
+  local component="$2"
+  local crd_json plural group scope resource stuck
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl:164]: This parses the same `crd_json` through `jq` three separate times (plural, group, scope). Could be a single call:
```bash
read -r plural group scope < <(echo "${crd_json}" | jq -r '[.spec.names.plural, .spec.group, .spec.scope] | @tsv' 2>/dev/null) || return 0
```
Minor efficiency concern — three `jq` processes per CRD adds up if a release has many CRDs (cert-manager has 6, gpu-operator has ~10).

File: pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl [hunk 3]
```diff
@@ -136,6 +148,93 @@ force_clear_namespace_finalizers() {
...
+
+  crd_json=$(kubectl get crd "${crd_name}" -o json 2>/dev/null) || return 0
+  plural=$(echo "${crd_json}" | jq -r '.spec.names.plural' 2>/dev/null) || return 0
+  group=$(echo "${crd_json}" | jq -r '.spec.group' 2>/dev/null) || return 0
+  scope=$(echo "${crd_json}" | jq -r '.spec.scope' 2>/dev/null) || return 0
+  [[ -z "${plural}" || "${plural}" == "null" ]] && return 0
+
+  resource="${plural}.${group}"
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl:170]: The check flags CRs with *any* non-empty `.metadata.finalizers`. Some finalizers are K8s-native (e.g., `kubernetes.io/pvc-protection`) and will be processed by K8s controllers regardless of whether the operator is running. These would be false positives.

In practice, CRDs owned by operators in the bundle are unlikely to have K8s-native finalizers, so this is probably fine. But if false positives surface, consider filtering to exclude `kubernetes.io/*` finalizers.

File: pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl [hunk 4]
```diff
@@ -136,6 +148,93 @@ force_clear_namespace_finalizers() {
...
+
+# Check a Helm release for CRDs whose custom resources have active finalizers.
+# Extracts CRD names from the release manifest and checks each one.
+# Silently skips releases that are not installed (helm get manifest fails).
+# Args: $1 = release name, $2 = namespace
+check_release_for_stuck_crds() {
+  local release="$1"
+  local ns="$2"
+  local manifest
+  manifest=$(helm get manifest "${release}" -n "${ns}" 2>/dev/null) || return 0
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl:198]: The awk CRD extraction works because Helm manifest output uses consistent YAML formatting: `kind:` at column 0, `  name:` at 2-space indent under `metadata:`. The `kind=""` reset after match prevents carry-over between documents. Looks solid for Helm output.

One edge case: if a CRD `metadata.name` contains special characters or spaces, `$2` would be truncated. Unlikely for CRD names (must be valid DNS), so this is fine.

File: pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl [hunk 5]
```diff
@@ -217,13 +314,21 @@ for group in ${ORPHANED_CRD_GROUPS}; do
...
+  echo ""
+  echo "WARNING: CRDs stuck in deleting state:"
   for crd in ${stuck_crds}; do
-    echo "Force-clearing finalizers on stuck CRD ${crd}..."
-    kubectl patch crd "${crd}" --type merge -p '{"metadata":{"finalizers":null}}' 2>/dev/null || true
+    echo "  ${crd}"
+  done
+  echo ""
+  echo "  To force-clear their finalizers (may orphan CR data in etcd):"
+  for crd in ${stuck_crds}; do
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl:343]: Good change. Silent force-clearing of CRD finalizers could orphan CR data in etcd — surfacing it as a warning with copy-paste remediation commands is safer and more transparent. The user retains control.

File: pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl [hunk 6]
```diff
@@ -18,23 +19,40 @@ SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
...
+echo ""
+echo "  The following components will be removed (in order):"
+{{ range .ComponentsReversed -}}
+{{ if .IsKustomize -}}
+printf "    \033[33m%-12s\033[0m %s (%s)\n" "[kustomize]" "{{ .Name }}" "{{ .Namespace }}"
+{{ else if .HasChart -}}
+printf "    \033[36m%-12s\033[0m %s (%s)\n" "[helm]" "{{ .Name }}" "{{ .Namespace }}"
+{{ else if .HasManifests -}}
+printf "    \033[35m%-12s\033[0m %s\n" "[manifests]" "{{ .Name }}"
+{{ end -}}
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl:60]: The component manifest with color-coded type tags is a nice UX touch. Showing exactly what will be removed before any destructive action is good practice.

Nit: the ANSI color codes won't render in non-TTY contexts (e.g., CI logs, `script` output piped to a file). Consider gating color output on `[[ -t 1 ]]` (stdout is a terminal), or it's fine to leave as-is since this is an interactive script.

File: pkg/bundler/deployer/helm/helm_test.go [hunk 7]
```diff
@@ -568,6 +568,63 @@ func TestGenerate_UndeployScriptExecutable(t *testing.T) {
...
+	if !strings.Contains(preflightSection, "PREFLIGHT_DETAILS") || !strings.Contains(preflightSection, "exit 1") {
+		t.Error("undeploy.sh pre-flight should detect stuck CRs and exit on failure")
+	}
+
+	// Verify pre-flight checks each Helm component (cert-manager and gpu-operator are in the test recipe)
+	if !strings.Contains(preflightSection, `check_release_for_stuck_crds "gpu-operator"`) {
+		t.Error("undeploy.sh pre-flight missing check for gpu-operator")
+	}
+	if !strings.Contains(preflightSection, `check_release_for_stuck_crds "cert-manager"`) {
+		t.Error("undeploy.sh pre-flight missing check for cert-manager")
```
Comment (mchmarny) [inline pkg/bundler/deployer/helm/helm_test.go]: The template generates two-arg calls: `check_release_for_stuck_crds "{{ .Name }}" "{{ .Namespace }}"`. This `strings.Contains` match on just `check_release_for_stuck_crds "gpu-operator"` passes because it's a substring, but it doesn't verify the namespace argument is present. Consider matching the full call including namespace:
```go
if !strings.Contains(preflightSection, `check_release_for_stuck_crds "gpu-operator" "gpu-operator"`) {
```
This ensures the template is actually emitting both arguments.

**Review by mchmarny — COMMENTED** [review]
Solid fix for a real operational pain point. The pre-flight check correctly targets the root cause (CRs with finalizers that become unresolvable after controller removal) and the approach — generic CRD discovery via `helm get manifest` rather than hardcoded CRD lists — is the right design.

**Should fix:**

1. **Predictable temp file** — `PREFLIGHT_DETAILS` uses a fixed path in `$TMPDIR`. Concurrent runs race on the same file, and the predictable name is a symlink-attack vector. Use `mktemp` with a random suffix.

2. **Test assertions too loose** — Pre-flight checks for `check_release_for_stuck_crds "gpu-operator"` pass via substring match but don't verify the namespace argument is present. The template emits two args — the test should match both.

**Worth considering:**

- Three separate `jq` invocations per CRD could be consolidated into one (minor perf for bundles with many CRDs)
- ANSI colors in the component manifest won't render when stdout is piped — gating on `[[ -t 1 ]]` would be polite
- The finalizer check flags *all* finalizers including K8s-native ones (`kubernetes.io/*`). Probably fine in practice since operator-owned CRDs rarely carry those, but could cause false positives.

**Looks good:**
- jq hard requirement simplification — removes ~8 branching guards, much cleaner
- Stuck CRD handling changed from silent force-clear to user-facing warning with copy-paste commands — safer
- awk-based CRD extraction from Helm manifest is correct for standard Helm output
- Optimistic concurrency pattern (pre-flight → check → exit or proceed) is clean
- `--skip-preflight` escape hatch is the right UX

File: pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl (hunk 5 above)
Comment (lockwobr) [reply pkg/bundler/deployer/helm/templates/undeploy.sh.tmpl:343]: done added
```
❯ ./undeploy.sh --skip-preflight --timeout 5
Undeploying Cloud Native Stack components (timeout: 5s)...

  The following components will be removed (in order):
    [helm]       nvsentinel (nvsentinel)
    [helm]       nvidia-dra-driver-gpu (nvidia-dra-driver)
    [helm]       kai-scheduler (kai-scheduler)
    [helm]       gpu-operator (gpu-operator)
    [manifests]  skyhook-customizations
    [helm]       skyhook-operator (skyhook)
    [helm]       prometheus-adapter (monitoring)
    [helm]       k8s-ephemeral-storage-metrics (monitoring)
    [helm]       kube-prometheus-stack (monitoring)
    [helm]       cert-manager (cert-manager)
    [helm]       aws-efa (kube-system)
    [helm]       aws-ebs-csi-driver (kube-system)

Skipping pre-flight checks (--skip-preflight).
Uninstalling nvsentinel (nvsentinel)...
release "nvsentinel" uninstalled
Uninstalling nvidia-dra-driver-gpu (nvidia-dra-driver)...
release "nvidia-dra-driver-gpu" uninstalled
Uninstalling kai-scheduler (kai-scheduler)...
release "kai-scheduler" uninstalled
Deleting manifests for gpu-operator...
Uninstalling gpu-operator (gpu-operator)...
release "gpu-operator" uninstalled
Deleting manifests for skyhook-customizations...
error: resource mapping not found for name: "tuning" namespace: "skyhook" from "/tmp/undeploy-test/bundle/skyhook-customizations/manifests/tuning.yaml": no matches for kind "Skyhook" in version "skyhook.nvidia.com/v1alpha1"
ensure CRDs are installed first
Uninstalling skyhook-operator (skyhook)...
release "skyhook-operator" uninstalled
Uninstalling prometheus-adapter (monitoring)...
release "prometheus-adapter" uninstalled
Uninstalling k8s-ephemeral-storage-metrics (monitoring)...
release "k8s-ephemeral-storage-metrics" uninstalled
Uninstalling kube-prometheus-stack (monitoring)...
release "kube-prometheus-stack" uninstalled
Uninstalling cert-manager (cert-manager)...
release "cert-manager" uninstalled
Deleting customresourcedefinitions/issuers.cert-manager.io...
customresourcedefinition.apiextensions.k8s.io "issuers.cert-manager.io" deleted
error: timed out waiting for the condition on customresourcedefinitions/issuers.cert-manager.io
Deleting customresourcedefinitions/orders.acme.cert-manager.io...
customresourcedefinition.apiextensions.k8s.io "orders.acme.cert-manager.io" deleted
Uninstalling aws-efa (kube-system)...
release "aws-efa" uninstalled
Uninstalling aws-ebs-csi-driver (kube-system)...
release "aws-ebs-csi-driver" uninstalled
Removing skyhook.nvidia.com node taints...
Deleting CRD issuers.cert-manager.io (owned by cert-manager/cert-manager)...
customresourcedefinition.apiextensions.k8s.io "issuers.cert-manager.io" deleted

WARNING: CRDs stuck in deleting state:
  issuers.cert-manager.io

  These CRDs have a deletionTimestamp but cannot complete deletion because
  their customresourcecleanup finalizer is waiting for CR instances to be
  removed. If you are certain no data will be lost, you can force-clear the
  finalizers. Note: this may leave orphaned CR data in etcd that is no longer
  accessible through the API.

  Commands to force-clear (review before running):
    kubectl patch crd issuers.cert-manager.io --type merge -p '{"metadata":{"finalizers":null}}'
Deleting namespace cert-manager...
namespace "cert-manager" deleted
Waiting for namespaces to terminate...
Post-flight: cluster is clean.
Undeployment complete.
```

**Review by mchmarny — APPROVED** [review]
